const CONSTANTS = {
    BUSCAR_POKEMON: 'BUSCAR_POKEMON',
    SAVE_POKEMON: 'SAVE_POKEMON',
    SHOW_LOADING: 'SHOW_LOADING',
    HIDE_LOADING: 'HIDE_LOADING',
    SHOW_INNER_LOADING: 'SHOW_INNER_LOADING',
    HIDE_INNER_LOADING: 'HIDE_INNER_LOADING',
    DATA_FORM_REGISTER: 'DATA_FORM_REGISTER',
  
  };
  
  export default CONSTANTS;
  